version: '2.4'
services:
  db:
    image: mysql
    container_name: library_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - library_db:/var/lib/mysql

volumes:
  library_db: