server:
  error:
    whitelabel:
      enabled: false
    include-message: always
    include_stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update